# Generated by Django 5.2.8 on 2025-11-24 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Banking', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Account',
            new_name='Customer',
        ),
    ]
